version: '3.9'
services:
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    networks:
      - movies-network

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - movies-network

networks:
  movies-network:
    name: movies-network
